---
layout: cv
title: Astella Ralston
---
# Astella Ralston
ral21002@byui.edu
Statistician, Mathematician, Aspiring Actuary

## About me

Hello! My name is Astella, I am from Flagstaff, Arizona currently attending Brigham Young University - Idaho. I am studying Statistics with the goal of being an actuary. I have always loved solving problems, especially those that I encounter in real life. I find mathematics to be the ultimate puzzle full of thinking and intrigue, viewing statistics as the bridge between theory and real world applications. In actuarial science, I utilize mathematics, programming, critical thinking, and problem solving skills to find solution to real world problems based on factual data. In addition to mathematics, I also love the outdoors, crafts, and writing. 

## Currently

A Junior Year Student in Rexburg, Idaho at Brigham Young University - Idaho, studying Statistics with an emphasis in Actuarial Science and a minor in Data Science. 

I am also actively studying to take the Financial Mathematics Actuarial Exam in June, working daily to reach 300 hours of overall study before taking to exam. 

### Specialized in

- Actuarial science
- Data Science and Programming

## Education

Brigham Young University - Idaho | 2021 - 2027 
Statistics - Actuarial Emphasis 

## Work Experience

College Mathematics Tutor and Lab Supervisor | 2024 - Present
- Used teaching and problem solving skills to improve grades by 85%
- Exercised leadership managing a team to assist 50-70 students at a given time
- Assist students in achieving academic goals by increasing skill and understanding in mathematical concepts.


